import './grant-role';
import './mint-batch';
import './pause';
import './renounce-role';
import './revoke-role';
import './set-base-uri';
import './set-payment-token';
import './set-treasury';
import './unpause';
