name: Solidity tests
on:
    push:
        paths-ignore:
            - '**.md'
            - 'ipfs/**'
jobs:
    run-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '22.14.0'
            - run: node --version
            - run: npm install
              working-directory: contract
            - run: npx hardhat compile
            - run: npm run test:ci
              working-directory: contract
